// src/vue/radio/Radio.vue
<script setup>
import { computed, onBeforeUnmount, onMounted, ref, useAttrs } from "vue";
import { twMerge } from "tailwind-merge";

defineOptions({ inheritAttrs: false });

const model = defineModel();
const attrs = useAttrs();
const element = ref();
let form;

const forwardedAttrs = computed(() => {
  const {
    class: _class,
    type: _type,
    checked: _checked,
    "data-slot": _dataSlot,
    "data-state": _dataState,
    "data-disabled": _dataDisabled,
    "data-invalid": _dataInvalid,
    ...rest
  } = attrs;
  return rest;
});

const disabled = computed(
  () => attrs.disabled !== undefined && attrs.disabled !== false,
);
const invalid = computed(
  () => attrs["aria-invalid"] === true || attrs["aria-invalid"] === "true",
);

function inputValue() {
  if (!element.value) return undefined;
  return Object.prototype.hasOwnProperty.call(element.value, "_value")
    ? element.value._value
    : element.value.value;
}

const checked = computed(() => Object.is(model.value, attrs.value ?? "on"));

function groupHasCheckedRadio() {
  if (!element.value) return false;
  const root = element.value.form ?? element.value.getRootNode();
  const controls =
    element.value.form?.elements ??
    root?.querySelectorAll?.('input[type="radio"]') ??
    [];

  return Array.from(controls).some(
    (control) =>
      control.type === "radio" &&
      control.name === element.value.name &&
      control.form === element.value.form &&
      control.checked,
  );
}

function resetModelFromElement() {
  if (element.value.checked) model.value = inputValue();
  else if (!groupHasCheckedRadio()) model.value = undefined;
}

function handleReset() {
  queueMicrotask(resetModelFromElement);
}

onMounted(() => {
  element.value.defaultChecked = element.value.checked;
  form = element.value.form;
  form?.addEventListener("reset", handleReset);
});

onBeforeUnmount(() => {
  form?.removeEventListener("reset", handleReset);
});

defineExpose({
  element,
  focus: (options) => element.value?.focus(options),
});
</script>

<template>
  <input
    ref="element"
    v-model="model"
    v-bind="forwardedAttrs"
    type="radio"
    data-slot="radio"
    :data-state="checked ? 'checked' : 'unchecked'"
    :data-disabled="disabled ? '' : undefined"
    :data-invalid="invalid ? '' : undefined"
    :class="
      twMerge(
        [
          'size-4 shrink-0 cursor-pointer appearance-auto accent-current text-gray-950 outline-none',
          'focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-gray-950',
          'disabled:cursor-not-allowed disabled:opacity-50',
          'aria-invalid:focus-visible:outline-red-600',
          'dark:text-white dark:focus-visible:outline-white dark:aria-invalid:focus-visible:outline-red-500',
        ],
        attrs.class,
      )
    "
  />
</template>

// registry/radio/react/Radio.jsx
import { forwardRef, useCallback, useEffect, useRef, useState } from "react";
import { twMerge } from "tailwind-merge";

const BASE_CLASSES = [
  "size-4 shrink-0 cursor-pointer appearance-auto accent-current text-gray-950 outline-none",
  "focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-gray-950",
  "disabled:cursor-not-allowed disabled:opacity-50",
  "aria-invalid:focus-visible:outline-red-600",
  "dark:text-white dark:focus-visible:outline-white dark:aria-invalid:focus-visible:outline-red-500",
];

function assignRef(ref, value) {
  if (typeof ref === "function") ref(value);
  else if (ref) ref.current = value;
}

const Radio = forwardRef(function Radio(
  {
    checked,
    defaultChecked = false,
    disabled = false,
    value = "on",
    "aria-invalid": ariaInvalid,
    className,
    onChange,
    "data-slot": _dataSlot,
    "data-state": _dataState,
    "data-disabled": _dataDisabled,
    "data-invalid": _dataInvalid,
    ...props
  },
  forwardedRef,
) {
  const elementRef = useRef(null);
  const controlled = checked !== undefined;
  const [localChecked, setLocalChecked] = useState(Boolean(defaultChecked));
  const resolvedChecked = controlled ? Boolean(checked) : localChecked;
  const invalid = ariaInvalid === true || ariaInvalid === "true";

  const setElement = useCallback(
    (node) => {
      elementRef.current = node;
      assignRef(forwardedRef, node);
    },
    [forwardedRef],
  );

  useEffect(() => {
    const node = elementRef.current;
    if (!node || controlled) return;

    const root = node.form ?? node.getRootNode();

    function syncGroupState(event) {
      const target = event.target;
      if (
        target?.type !== "radio" ||
        target.name !== node.name ||
        target.form !== node.form
      ) {
        return;
      }

      setLocalChecked(node.checked);
    }

    function handleReset() {
      queueMicrotask(() => setLocalChecked(node.checked));
    }

    root?.addEventListener("change", syncGroupState);
    node.form?.addEventListener("reset", handleReset);

    return () => {
      root?.removeEventListener("change", syncGroupState);
      node.form?.removeEventListener("reset", handleReset);
    };
  }, [controlled]);

  function handleChange(event) {
    if (!controlled) setLocalChecked(event.target.checked);
    onChange?.(event);
  }

  return (
    <input
      {...props}
      ref={setElement}
      type="radio"
      checked={controlled ? Boolean(checked) : undefined}
      defaultChecked={controlled ? undefined : Boolean(defaultChecked)}
      disabled={disabled}
      value={value}
      aria-invalid={ariaInvalid}
      data-slot="radio"
      data-state={resolvedChecked ? "checked" : "unchecked"}
      data-disabled={disabled ? "" : undefined}
      data-invalid={invalid ? "" : undefined}
      className={twMerge(BASE_CLASSES, className)}
      onChange={handleChange}
    />
  );
});

export default Radio;
