// src/vue/table/Table.vue
<script setup>
import { computed, ref, useAttrs } from "vue";
import { twMerge } from "tailwind-merge";

defineOptions({ inheritAttrs: false });

const attrs = useAttrs();
const element = ref();

const forwardedAttrs = computed(() => {
  const { class: _class, "data-slot": _dataSlot, ...rest } = attrs;
  return rest;
});

defineExpose({ element });
</script>

<template>
  <table
    ref="element"
    v-bind="forwardedAttrs"
    data-slot="table"
    :class="
      twMerge(
        'w-full border-collapse text-left text-sm text-gray-950 dark:text-white',
        attrs.class,
      )
    "
  >
    <slot />
  </table>
</template>

// registry/table/react/Table.jsx
import { forwardRef } from "react";
import { twMerge } from "tailwind-merge";

const BASE_CLASSES =
  "w-full border-collapse text-left text-sm text-gray-950 dark:text-white";

const Table = forwardRef(function Table(
  { className, "data-slot": _dataSlot, ...props },
  ref,
) {
  return (
    <table
      {...props}
      ref={ref}
      data-slot="table"
      className={twMerge(BASE_CLASSES, className)}
    />
  );
});

export default Table;
