// src/vue/data-table/DataTable.vue
<script setup>
import { computed, ref, useAttrs, watch } from "vue";
import { twMerge } from "tailwind-merge";
import Table from "../table/Table.vue";

defineOptions({ inheritAttrs: false });

const props = defineProps({
  rows: { type: Array, default: () => [] },
  rowKey: { type: [String, Function], default: "id" },
  selectable: { type: Function, default: () => true },
  busy: { type: Boolean, default: false },
  tableClass: { type: [String, Array, Object], default: undefined },
});

const selected = defineModel("selected", { default: () => [] });
const attrs = useAttrs();
const root = ref();

const rootAttrs = computed(() => {
  const {
    class: _class,
    "data-slot": _dataSlot,
    "data-busy": _dataBusy,
    "data-empty": _dataEmpty,
    ...rest
  } = attrs;
  return rest;
});

function keyFor(row) {
  return typeof props.rowKey === "function"
    ? props.rowKey(row)
    : row?.[props.rowKey];
}

function canSelect(row) {
  return props.selectable(row) !== false;
}

const selectableKeys = computed(() => props.rows.filter(canSelect).map(keyFor));
const selectableKeySet = computed(() => new Set(selectableKeys.value));
const selectedKeySet = computed(() => new Set(selected.value));
const selectedCount = computed(() => selectedKeySet.value.size);
const allSelected = computed(
  () =>
    selectableKeys.value.length > 0 &&
    selectableKeys.value.every((key) => selectedKeySet.value.has(key)),
);
const someSelected = computed(
  () => selectedCount.value > 0 && !allSelected.value,
);
const status = computed(() => {
  if (selectedCount.value === 0) return "No rows selected.";
  return `${selectedCount.value} row${selectedCount.value === 1 ? "" : "s"} selected.`;
});

function setSelected(next) {
  selected.value = [...new Set(next)];
}

function isSelected(row) {
  return selectedKeySet.value.has(keyFor(row));
}

function setRowSelected(row, checked) {
  if (props.busy || !canSelect(row)) return;
  const key = keyFor(row);
  const next = new Set(selected.value);
  if (checked) next.add(key);
  else next.delete(key);
  setSelected(next);
}

function setPageSelected(checked) {
  if (props.busy) return;
  setSelected(checked ? selectableKeys.value : []);
}

function clearSelection() {
  setSelected([]);
}

function removeSelection(keys) {
  const removed = new Set(Array.isArray(keys) ? keys : [keys]);
  setSelected(selected.value.filter((key) => !removed.has(key)));
}

function rowSelection(row, label) {
  const key = keyFor(row);
  return {
    modelValue: selectedKeySet.value.has(key),
    disabled: props.busy || !canSelect(row),
    "aria-label": label || `Select row ${String(key)}`,
    "onUpdate:modelValue": (checked) => setRowSelected(row, checked),
  };
}

function pageSelection(label = "Select all rows on this page") {
  return {
    modelValue: allSelected.value,
    indeterminate: someSelected.value,
    disabled: props.busy || selectableKeys.value.length === 0,
    "aria-label": label,
    "onUpdate:modelValue": setPageSelected,
  };
}

watch(
  selectableKeySet,
  (keys) => {
    const next = selected.value.filter((key) => keys.has(key));
    if (
      next.length !== selected.value.length ||
      next.some((key, index) => !Object.is(key, selected.value[index]))
    ) {
      setSelected(next);
    }
  },
  { immediate: true, flush: "sync" },
);

defineExpose({
  root,
  clearSelection,
  removeSelection,
});
</script>

<template>
  <div
    ref="root"
    v-bind="rootAttrs"
    data-slot="data-table"
    :data-busy="busy ? '' : undefined"
    :data-empty="rows.length === 0 ? '' : undefined"
    :class="twMerge('relative overflow-x-auto', attrs.class)"
  >
    <Table
      :aria-busy="busy ? 'true' : undefined"
      :class="twMerge('min-w-full', tableClass)"
    >
      <slot
        :rows="rows"
        :selected="selected"
        :selected-count="selectedCount"
        :all-selected="allSelected"
        :some-selected="someSelected"
        :is-selected="isSelected"
        :row-selection="rowSelection"
        :page-selection="pageSelection"
        :clear-selection="clearSelection"
        :remove-selection="removeSelection"
      />
    </Table>
    <span class="sr-only" aria-live="polite" aria-atomic="true">{{
      status
    }}</span>
  </div>
</template>

// registry/data-table/react/DataTable.jsx
import {
  forwardRef,
  useEffect,
  useImperativeHandle,
  useMemo,
  useRef,
  useState,
} from "react";
import { twMerge } from "tailwind-merge";
import Table from "../table/Table.jsx";

const DataTable = forwardRef(function DataTable(
  {
    rows = [],
    rowKey = "id",
    selectable = () => true,
    busy = false,
    selected,
    defaultSelected = [],
    onSelectedChange,
    tableClassName,
    className,
    children,
    "data-slot": _dataSlot,
    "data-busy": _dataBusy,
    "data-empty": _dataEmpty,
    ...props
  },
  forwardedRef,
) {
  const rootRef = useRef(null);
  const controlled = selected !== undefined;
  const [localSelected, setLocalSelected] = useState(defaultSelected);
  const selectedKeys = controlled ? selected : localSelected;

  function keyFor(row) {
    return typeof rowKey === "function" ? rowKey(row) : row?.[rowKey];
  }

  const selectableKeys = useMemo(
    () => rows.filter((row) => selectable(row) !== false).map(keyFor),
    [rows, rowKey, selectable],
  );
  const selectableKeySet = useMemo(
    () => new Set(selectableKeys),
    [selectableKeys],
  );
  const selectedKeySet = useMemo(() => new Set(selectedKeys), [selectedKeys]);
  const allSelected =
    selectableKeys.length > 0 &&
    selectableKeys.every((key) => selectedKeySet.has(key));
  const someSelected = selectedKeySet.size > 0 && !allSelected;

  function setSelected(next) {
    const value = [...new Set(next)];
    if (!controlled) setLocalSelected(value);
    onSelectedChange?.(value);
  }

  function isSelected(row) {
    return selectedKeySet.has(keyFor(row));
  }

  function setRowSelected(row, checked) {
    if (busy || selectable(row) === false) return;
    const key = keyFor(row);
    const next = new Set(selectedKeys);
    if (checked) next.add(key);
    else next.delete(key);
    setSelected(next);
  }

  function setPageSelected(checked) {
    if (busy) return;
    setSelected(checked ? selectableKeys : []);
  }

  function clearSelection() {
    setSelected([]);
  }

  function removeSelection(keys) {
    const removed = new Set(Array.isArray(keys) ? keys : [keys]);
    setSelected(selectedKeys.filter((key) => !removed.has(key)));
  }

  function rowSelection(row, label) {
    const key = keyFor(row);
    return {
      checked: selectedKeySet.has(key),
      disabled: busy || selectable(row) === false,
      "aria-label": label || `Select row ${String(key)}`,
      onChange: (event) => setRowSelected(row, event.currentTarget.checked),
    };
  }

  function pageSelection(label = "Select all rows on this page") {
    return {
      checked: allSelected,
      indeterminate: someSelected,
      disabled: busy || selectableKeys.length === 0,
      "aria-label": label,
      onChange: (event) => setPageSelected(event.currentTarget.checked),
    };
  }

  useEffect(() => {
    const next = selectedKeys.filter((key) => selectableKeySet.has(key));
    if (
      next.length !== selectedKeys.length ||
      next.some((key, index) => !Object.is(key, selectedKeys[index]))
    ) {
      setSelected(next);
    }
  }, [selectableKeySet, selectedKeys]);

  useImperativeHandle(forwardedRef, () => ({
    root: rootRef.current,
    clearSelection,
    removeSelection,
  }));

  const api = {
    rows,
    selected: selectedKeys,
    selectedCount: selectedKeySet.size,
    allSelected,
    someSelected,
    isSelected,
    rowSelection,
    pageSelection,
    clearSelection,
    removeSelection,
  };
  const status =
    selectedKeySet.size === 0
      ? "No rows selected."
      : `${selectedKeySet.size} row${selectedKeySet.size === 1 ? "" : "s"} selected.`;

  return (
    <div
      {...props}
      ref={rootRef}
      data-slot="data-table"
      data-busy={busy ? "" : undefined}
      data-empty={rows.length === 0 ? "" : undefined}
      className={twMerge("relative overflow-x-auto", className)}
    >
      <Table
        aria-busy={busy ? "true" : undefined}
        className={twMerge("min-w-full", tableClassName)}
      >
        {typeof children === "function" ? children(api) : children}
      </Table>
      <span className="sr-only" aria-live="polite" aria-atomic="true">
        {status}
      </span>
    </div>
  );
});

export default DataTable;
