// registry/popover/react/Popover.jsx
import {
  autoUpdate,
  computePosition,
  flip,
  offset as floatingOffset,
  shift,
} from "@floating-ui/dom";
import {
  forwardRef,
  useCallback,
  useEffect,
  useId,
  useImperativeHandle,
  useRef,
  useState,
} from "react";
import { twMerge } from "tailwind-merge";

const BASE_CLASSES = [
  "z-50 m-0 w-max max-w-[calc(100vw-1rem)] rounded-md border border-gray-200 bg-white p-4 text-gray-950 shadow-lg outline-none",
  "dark:border-gray-700 dark:bg-gray-950 dark:text-white",
];

const Popover = forwardRef(function Popover(
  {
    id,
    open: controlledOpen,
    defaultOpen = false,
    onOpenChange,
    placement = "bottom-start",
    offset = 8,
    className,
    style,
    children,
    ...contentProps
  },
  forwardedRef,
) {
  const generatedId = useId().replace(/[^a-zA-Z0-9_-]/g, "");
  const contentId = id ?? `klean-popover-${generatedId}`;
  const contentRef = useRef(null);
  const activeInvoker = useRef(null);
  const [internalOpen, setInternalOpen] = useState(defaultOpen);
  const [supportsNative, setSupportsNative] = useState(false);
  const [resolvedPlacement, setResolvedPlacement] = useState(placement);
  const [positionStyle, setPositionStyle] = useState({
    position: "fixed",
    left: 0,
    top: 0,
  });
  const isControlled = controlledOpen !== undefined;
  const isOpen = isControlled ? controlledOpen : internalOpen;
  const latestOpen = useRef(isOpen);
  latestOpen.current = isOpen;

  const invokers = useCallback(() => {
    const root = contentRef.current?.getRootNode?.() ?? document;

    return [...(root.querySelectorAll?.("[popovertarget]") ?? [])].filter(
      (element) => element.getAttribute("popovertarget") === contentId,
    );
  }, [contentId]);

  const eventPath = (event) =>
    event.nativeEvent?.composedPath?.() ??
    event.composedPath?.() ?? [event.target];

  const resolveInvoker = useCallback(
    (candidate) => {
      if (candidate?.getAttribute?.("popovertarget") === contentId) {
        activeInvoker.current = candidate;
      }

      if (!activeInvoker.current?.isConnected) {
        activeInvoker.current = invokers()[0];
      }

      return activeInvoker.current;
    },
    [contentId, invokers],
  );

  const syncInvokerAria = useCallback(() => {
    for (const invoker of invokers()) {
      invoker.setAttribute("aria-controls", contentId);
      invoker.setAttribute("aria-expanded", String(latestOpen.current));
    }
  }, [contentId, invokers]);

  const popoverIsShowing = useCallback(() => {
    if (!supportsNative || !contentRef.current) return false;

    try {
      return contentRef.current.matches(":popover-open");
    } catch {
      return false;
    }
  }, [supportsNative]);

  const syncNativePopover = useCallback(() => {
    if (!supportsNative || !contentRef.current) return;

    const showing = popoverIsShowing();

    try {
      if (latestOpen.current && !showing) {
        contentRef.current.showPopover({ source: resolveInvoker() });
      } else if (!latestOpen.current && showing) {
        contentRef.current.hidePopover();
      }
    } catch {
      // A rapid native toggle can briefly make the requested state redundant.
    }
  }, [popoverIsShowing, resolveInvoker, supportsNative]);

  const requestOpen = useCallback(
    (nextOpen, { restoreFocus = false } = {}) => {
      if (!isControlled) setInternalOpen(nextOpen);
      onOpenChange?.(nextOpen);

      queueMicrotask(() => {
        syncInvokerAria();
        syncNativePopover();

        const invoker = resolveInvoker();
        if (!nextOpen && restoreFocus && invoker?.isConnected) {
          invoker.focus({ preventScroll: true });
        }
      });
    },
    [
      isControlled,
      onOpenChange,
      resolveInvoker,
      syncInvokerAria,
      syncNativePopover,
    ],
  );

  useImperativeHandle(
    forwardedRef,
    () => ({
      content: contentRef.current,
      open: () => requestOpen(true),
      close: () => requestOpen(false, { restoreFocus: true }),
    }),
    [requestOpen],
  );

  useEffect(() => {
    const native =
      typeof contentRef.current?.showPopover === "function" &&
      typeof contentRef.current?.hidePopover === "function";
    setSupportsNative(native);
    resolveInvoker();
    syncInvokerAria();

    if (native) return;

    function handleFallbackInvokerClick(event) {
      const candidate = eventPath(event).find(
        (element) => element?.getAttribute?.("popovertarget") === contentId,
      );
      if (candidate?.getAttribute("popovertarget") !== contentId) return;

      resolveInvoker(candidate);
      const action = candidate.getAttribute("popovertargetaction") ?? "toggle";

      if (action === "show") requestOpen(true);
      else if (action === "hide") {
        requestOpen(false, { restoreFocus: true });
      } else requestOpen(!latestOpen.current);
    }

    document.addEventListener("click", handleFallbackInvokerClick);
    return () =>
      document.removeEventListener("click", handleFallbackInvokerClick);
  }, [contentId, requestOpen, resolveInvoker, syncInvokerAria]);

  useEffect(() => {
    syncInvokerAria();
    syncNativePopover();

    const invoker = resolveInvoker();
    if (!isOpen || !invoker || !contentRef.current) return;

    const updatePosition = async () => {
      const result = await computePosition(invoker, contentRef.current, {
        placement,
        strategy: "fixed",
        middleware: [floatingOffset(offset), flip(), shift({ padding: 8 })],
      });

      setResolvedPlacement(result.placement);
      setPositionStyle({ position: "fixed", left: result.x, top: result.y });
    };

    return autoUpdate(invoker, contentRef.current, updatePosition);
  }, [
    isOpen,
    offset,
    placement,
    resolveInvoker,
    syncInvokerAria,
    syncNativePopover,
  ]);

  useEffect(() => {
    if (!isOpen) return;

    function handleOutsidePointer(event) {
      const path = eventPath(event);

      if (
        path.includes(contentRef.current) ||
        invokers().some(
          (invoker) => path.includes(invoker) || invoker.contains(event.target),
        )
      ) {
        return;
      }

      requestOpen(false);
    }

    function handleEscape(event) {
      if (event.key !== "Escape") return;

      if (supportsNative) {
        const openPopovers = [...document.querySelectorAll(":popover-open")];
        if (openPopovers.at(-1) !== contentRef.current) return;
      }

      event.preventDefault();
      requestOpen(false, { restoreFocus: true });
    }

    document.addEventListener("keydown", handleEscape);
    document.addEventListener("pointerdown", handleOutsidePointer, true);

    return () => {
      document.removeEventListener("pointerdown", handleOutsidePointer, true);
      document.removeEventListener("keydown", handleEscape);
    };
  }, [isOpen, invokers, requestOpen, supportsNative]);

  function handleNativeToggle(event) {
    const nativeEvent = event.nativeEvent;
    const nextOpen = nativeEvent.newState === "open";
    const shouldRestoreFocus =
      !nextOpen &&
      nativeEvent.source?.getAttribute?.("popovertargetaction") === "hide";
    if (nextOpen) resolveInvoker(nativeEvent.source);
    if (nextOpen === latestOpen.current) return;

    if (!isControlled) setInternalOpen(nextOpen);
    onOpenChange?.(nextOpen);
    queueMicrotask(syncInvokerAria);

    if (isControlled) queueMicrotask(syncNativePopover);

    if (shouldRestoreFocus) {
      queueMicrotask(() => {
        const invoker = resolveInvoker();
        if (invoker?.isConnected) invoker.focus({ preventScroll: true });
      });
    }
  }

  const close = () => requestOpen(false, { restoreFocus: true });

  return (
    <div
      {...contentProps}
      ref={contentRef}
      id={contentId}
      popover="auto"
      hidden={!supportsNative && !isOpen}
      data-slot="popover-content"
      data-state={isOpen ? "open" : "closed"}
      data-placement={resolvedPlacement}
      className={twMerge(BASE_CLASSES, className)}
      style={{ ...positionStyle, ...style }}
      onToggle={handleNativeToggle}
    >
      {typeof children === "function"
        ? children({ open: isOpen, close })
        : children}
    </div>
  );
});

export default Popover;

// registry/popover/svelte/Popover.svelte
<script>
  import {
    autoUpdate,
    computePosition,
    flip,
    offset as floatingOffset,
    shift,
  } from "@floating-ui/dom";
  import { onMount, untrack } from "svelte";
  import { twMerge } from "tailwind-merge";

  const BASE_CLASSES = [
    "z-50 m-0 w-max max-w-[calc(100vw-1rem)] rounded-md border border-gray-200 bg-white p-4 text-gray-950 shadow-lg outline-none",
    "dark:border-gray-700 dark:bg-gray-950 dark:text-white",
  ];

  let {
    id,
    open = $bindable(),
    defaultOpen = false,
    onOpenChange,
    placement = "bottom-start",
    offset = 8,
    class: className = "",
    style,
    children,
    ...contentProps
  } = $props();

  const componentId = $props.id();
  const generatedId = `klean-popover-${componentId}`;
  let internalOpen = $state(untrack(() => defaultOpen));
  let contentElement = $state();
  let activeInvoker = $state();
  let supportsNative = $state(false);
  let resolvedPlacement = $state(untrack(() => placement));
  let positionStyle = $state({ position: "fixed", left: "0px", top: "0px" });
  let isOpen = $derived(open ?? internalOpen);
  let contentId = $derived(id ?? generatedId);
  let mergedStyle = $derived(
    typeof style === "string"
      ? `position:${positionStyle.position};left:${positionStyle.left};top:${positionStyle.top};${style}`
      : { ...positionStyle, ...style },
  );

  function invokers() {
    const root = contentElement?.getRootNode?.() ?? document;

    return [...(root.querySelectorAll?.("[popovertarget]") ?? [])].filter(
      (element) => element.getAttribute("popovertarget") === contentId,
    );
  }

  function eventPath(event) {
    return event.composedPath?.() ?? [event.target];
  }

  function resolveInvoker(candidate) {
    if (candidate?.getAttribute?.("popovertarget") === contentId) {
      activeInvoker = candidate;
    }

    if (!activeInvoker?.isConnected) activeInvoker = invokers()[0];
    return activeInvoker;
  }

  function syncInvokerAria() {
    for (const invoker of invokers()) {
      invoker.setAttribute("aria-controls", contentId);
      invoker.setAttribute("aria-expanded", String(isOpen));
    }
  }

  function popoverIsShowing() {
    if (!supportsNative || !contentElement) return false;

    try {
      return contentElement.matches(":popover-open");
    } catch {
      return false;
    }
  }

  function syncNativePopover() {
    if (!supportsNative || !contentElement) return;

    const showing = popoverIsShowing();

    try {
      if (isOpen && !showing) {
        contentElement.showPopover({ source: resolveInvoker() });
      } else if (!isOpen && showing) {
        contentElement.hidePopover();
      }
    } catch {
      // A rapid native toggle can briefly make the requested state redundant.
    }
  }

  function requestOpen(nextOpen, { restoreFocus = false } = {}) {
    if (open === undefined) internalOpen = nextOpen;
    else open = nextOpen;
    onOpenChange?.(nextOpen);

    queueMicrotask(() => {
      syncInvokerAria();
      syncNativePopover();

      const invoker = resolveInvoker();
      if (!nextOpen && restoreFocus && invoker?.isConnected) {
        invoker.focus({ preventScroll: true });
      }
    });
  }

  function close() {
    requestOpen(false, { restoreFocus: true });
  }

  export function getContent() {
    return contentElement;
  }

  function handleNativeToggle(event) {
    const nextOpen = event.newState === "open";
    const shouldRestoreFocus =
      !nextOpen &&
      event.source?.getAttribute?.("popovertargetaction") === "hide";
    if (nextOpen) resolveInvoker(event.source);
    if (nextOpen === isOpen) return;

    if (open === undefined) internalOpen = nextOpen;
    else open = nextOpen;
    onOpenChange?.(nextOpen);
    queueMicrotask(syncInvokerAria);

    if (shouldRestoreFocus) {
      queueMicrotask(() => {
        const invoker = resolveInvoker();
        if (invoker?.isConnected) invoker.focus({ preventScroll: true });
      });
    }
  }

  onMount(() => {
    supportsNative =
      typeof contentElement?.showPopover === "function" &&
      typeof contentElement?.hidePopover === "function";
    resolveInvoker();
    syncInvokerAria();

    if (supportsNative) return;

    function handleFallbackInvokerClick(event) {
      const candidate = eventPath(event).find(
        (element) => element?.getAttribute?.("popovertarget") === contentId,
      );
      if (candidate?.getAttribute("popovertarget") !== contentId) return;

      resolveInvoker(candidate);
      const action = candidate.getAttribute("popovertargetaction") ?? "toggle";

      if (action === "show") requestOpen(true);
      else if (action === "hide") {
        requestOpen(false, { restoreFocus: true });
      } else requestOpen(!isOpen);
    }

    document.addEventListener("click", handleFallbackInvokerClick);
    return () =>
      document.removeEventListener("click", handleFallbackInvokerClick);
  });

  $effect(() => {
    syncInvokerAria();
    syncNativePopover();

    const invoker = resolveInvoker();
    if (!isOpen || !invoker || !contentElement) return;

    const updatePosition = async () => {
      const result = await computePosition(invoker, contentElement, {
        placement,
        strategy: "fixed",
        middleware: [
          floatingOffset(offset),
          flip(),
          shift({ padding: 8 }),
        ],
      });

      resolvedPlacement = result.placement;
      positionStyle = {
        position: "fixed",
        left: `${result.x}px`,
        top: `${result.y}px`,
      };
    };

    return autoUpdate(invoker, contentElement, updatePosition);
  });

  $effect(() => {
    if (!isOpen) return;

    function handleOutsidePointer(event) {
      const path = eventPath(event);

      if (
        path.includes(contentElement) ||
        invokers().some(
          (invoker) => path.includes(invoker) || invoker.contains(event.target),
        )
      ) {
        return;
      }

      requestOpen(false);
    }

    function handleEscape(event) {
      if (event.key !== "Escape") return;

      if (supportsNative) {
        const openPopovers = [...document.querySelectorAll(":popover-open")];
        if (openPopovers.at(-1) !== contentElement) return;
      }

      event.preventDefault();
      requestOpen(false, { restoreFocus: true });
    }

    document.addEventListener("keydown", handleEscape);
    document.addEventListener("pointerdown", handleOutsidePointer, true);

    return () => {
      document.removeEventListener("pointerdown", handleOutsidePointer, true);
      document.removeEventListener("keydown", handleEscape);
    };
  });
</script>

<div
  {...contentProps}
  bind:this={contentElement}
  id={contentId}
  popover="auto"
  hidden={!supportsNative && !isOpen}
  data-slot={contentProps["data-slot"] ?? "popover-content"}
  data-state={isOpen ? "open" : "closed"}
  data-placement={resolvedPlacement}
  class={twMerge(BASE_CLASSES, className)}
  style={mergedStyle}
  ontoggle={handleNativeToggle}
>
  {@render children?.({ open: isOpen, close })}
</div>
