// registry/empty-state/react/EmptyState.jsx
import { forwardRef } from "react";
import { twMerge } from "tailwind-merge";

const BASE_CLASSES =
  "flex min-h-48 w-full flex-col items-center justify-center gap-4 p-6 text-center text-gray-950 dark:text-white";

const EmptyState = forwardRef(function EmptyState(
  { as: Component = "div", className, "data-slot": _dataSlot, ...props },
  ref,
) {
  return (
    <Component
      {...props}
      ref={ref}
      data-slot="empty-state"
      className={twMerge(BASE_CLASSES, className)}
    />
  );
});

export default EmptyState;

// src/vue/empty-state/EmptyState.vue
<script setup>
import { computed, ref, useAttrs } from "vue";
import { twMerge } from "tailwind-merge";

defineOptions({ inheritAttrs: false });

defineProps({
  /** Native element or framework component that truthfully fits the document. */
  as: { type: [String, Object, Function], default: "div" },
});

const attrs = useAttrs();
const element = ref();
const rootAttrs = computed(() => {
  const { class: _class, "data-slot": _dataSlot, ...rest } = attrs;
  return rest;
});

defineExpose({ element });
</script>

<template>
  <component
    :is="as"
    ref="element"
    v-bind="rootAttrs"
    data-slot="empty-state"
    :class="
      twMerge(
        'flex min-h-48 w-full flex-col items-center justify-center gap-4 p-6 text-center text-gray-950 dark:text-white',
        attrs.class,
      )
    "
  >
    <slot />
  </component>
</template>
